---
title: "Capstone Project Ideas"
output: md_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#### Idea 1: Evaluate customer experience through Amazon product reviews 

Customer experience is a multidimensional marketing construct focusing on a
customer's cognitive, emotional, behavioral, sensorial, and social
responses to a firm's offerings during the customer's entire purchase
journey. Research has shown that a positive customer experience is related 
to customer satisfaction. Customer satisfaction is crucial because it 
determines the long-term success of a company. The measuring of customer 
experience contains the following six dimensions:

- Sensorial, Emotional, Cognitive,  Pragmatic, Lifestyle and Relational  

There is a data set available that contains product reviews and metadata 
from Amazon, including 142.8 million reviews spanning May 1996 - July 2014.
This dataset includes reviews (ratings, text, helpfulness votes), 
product metadata (descriptions, category information, price, brand, 
and image features). 

<http://jmcauley.ucsd.edu/data/amazon/>

The Idea is to measure the customer experience through a automatic
content analyses or text-mining and relate the results to the ratings of the products
(customer satisfaction). This would give companies a fast and easy insight of the customer experience of their customers and the opportunity to improve the customer experience in certain areas. 
 

#### Idea 2: Predicting the sales of Walmart

Walmart is a large international discount retail chain. The company runs several promotional markdown events throughout the year. These markdowns precede prominent holidays, the four largest of which are the Super Bowl, Labor Day, Thanksgiving, and Christmas. There is a data
set available which provideds historical sales data for 45 Walmart stores located in different regions. Each store contains a certain number of departments.

<https://www.kaggle.com/c/walmart-recruiting-store-sales-forecasting/data> 

The Idea is to predict the sales of Walmart. Because the promotions are expensive it would
be interesting to evaluate if they pay off. Further more, predicting sales would give the buying stuff a better planning security. 


#### Idea 3: Predicting positive reviews in Yelp

Yelp is an internet portal which contains reviews about local businesses. The quality of
the reviews have a strong influence on the behavior of potential customers and the
overall image of a certain businesss. If a business has positive reviews it appears at the top
of the list and the probability increases the customers choose such a business. There is a data set of Yelp available that contains information about local businesses in 12 metropolitan areas across 4 countries. 

<https://www.yelp.de/dataset/challenge> 

The idea is to predict the rating of a business through different characteristics like city, state, categories or attributes. This would give the firms the opportunity to evaluate
which characteristics in a certain business are crucial for being successful. 



